# Generated by Django 2.2.7 on 2019-11-30 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
